Dynamically generate the login screen
openhab/openhabian pull request #1338
Opened 2020-12-28 01:08 UTC by ecdye

Fixes: #1273

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

2020-12-28 01:09 UTC, ecdye commented
@mstormi Will this work? I think it will be much simpler and save me a lot a coding.

2020-12-28 09:52 UTC, mstormi commented
No I don't think so. If someone changes branch but does un/reinstall OH it will not.
Also .bash_profile should not be system-manager, users should be able to edit it.

> and save me a lot a coding.

now that explains your reluctance but I don't understand why you think it is much coding ? what about [my proposal ](https://github.com/openhab/openhabian/issues/1273#issuecomment-749805493) ? That's just the extended version of what you did here, isn't it.

2020-12-28 20:29 UTC, ecdye commented
The issue is that the banner is generated with certain components that are sourced from dpkg and others.

I dont see how I can circumvent that sourcing of version components without some very hacky coding.

2020-12-29 10:15 UTC, mstormi commented
You mean this part?
```
OHVERSION=$(dpkg-query --showformat='${Version}' --show openhab2)
OHBUILD=$(sed -n 's/build-no\s*: //p' /var/lib/openhab2/etc/version.properties)
if [ "$OHBUILD" == "- release build -" ]; then OHBUILD="Release Build"; fi
```


source /opt/openhabian/functions/openhab.bash
if openhab3_is_installed; then OHPKG=openhab; else OHPKG=openhab2; fi

Then use $OHPKG instead of openhab2

or what else?

2020-12-29 22:30 UTC, mstormi requested changes
comments see last post

2020-12-29 23:17 UTC, ecdye commented
> is there anything else that you believe you need hacky coding for to be circumvented?

Yeah how would I get the banner to take that input, the substitution of the variables happens in the banner itself and IIRC `cat` wont make the variable substitutions.

2020-12-29 23:23 UTC, mstormi commented
use sed like we do in some locations (e.g. Amanda) to replace strings in templates in the includes/ dir

2020-12-29 23:25 UTC, ecdye commented
Sounds good, gotta love when you just hit a wall. I'll work on this in the coming days. I won't have time to finish it tonight.

2020-12-29 23:28 UTC, mstormi commented
FWIW I just discovered that openhabian.conf replacement didn't work in some cases on my own machine
Right after merging the PR, of course.
So quickly manually commented that out for now in both, master and openHAB3

2020-12-30 00:28 UTC, mstormi commented
> FWIW I just discovered that openhabian.conf replacement didn't work in some cases

found, fixed & uploaded

2021-01-04 09:02 UTC, mstormi commented
any progress, or did you hit another wall ?

2021-01-04 15:44 UTC, ecdye commented
Haven't had time to start yet, but this is this weeks main project for me.

2021-01-07 22:11 UTC, mstormi requested changes
Just change the text to be more useful for users then we should be done and can merge

2021-01-07 22:11 UTC, mstormi commented on includes/bash_profile
> +  echo -e -n "\\n\e[31;01mAttention! \e[39;49;00m"
see https://github.com/openhab/openhabian/pull/1392#discussion_r553246870

2021-01-07 22:57 UTC, ecdye commented on includes/bash_profile
> +  echo -e -n "\\n\e[31;01mAttention! \e[39;49;00m"
Will do when I have time.

2021-01-08 16:22 UTC, mstormi approved these changes

2021-01-08 16:23 UTC, merged