Added dark theme to frontail for openHAB3 branch
openhab/openhabian pull request #1391
Opened 2021-01-06 19:20 UTC by florian-h05

I have added a dark theme for the openHAB log viewer (frontail) in the openHAB3 branch.

You can select the darkmode by using the openhabian-config tool, when running in unattended mode the theme is set to the light theme as a default.

2021-01-06 19:22 UTC, florian-h05 commented
@ecdye 
My new pull request, the old one was #1388.

2021-01-08 09:24 UTC, florian-h05 commented
Rebased the _florian-h05:frontail2_ branch from _openhab:openHAB3_ with the latest changed

2021-01-08 09:50 UTC, florian-h05 commented
Signed-off-by: Florian Hotze <fhgames18@icloud.com>

2021-01-08 11:04 UTC, mstormi requested changes

2021-01-08 11:04 UTC, mstormi commented on functions/nodejs-apps.bash
> +      22\ *)  echo -n "$(timestamp) [openHABian] Setting up openHAB Log Viewer (frontail) service with dark theme..."
do not create another frontail service file but make the theme a _parameter_.
Replace in the template as it's done with %FRONTAILBASE with another -e argument to sed

2021-01-08 12:13 UTC, florian-h05 commented on includes/frontail-theme.css
> +@import 'default.css';
When not importing the _default.css_, which imports the _bootstrap.min.css_ from the url, frontail looks very different to the "old" frontail design in openhab2. 
For example the title bar is scrolling away now, in the past it was pinned at the top of the screen.

Therefore I think that we need _default.css_.

2021-01-08 13:03 UTC, florian-h05 commented on functions/nodejs-apps.bash
> +  if cond_redirect systemctl restart frontail.service; then echo "OK"; else echo "Failed (restart service)"; return 1; fi
Hmm, okay. On my machine I need to restart the frontail service to make the theme change visible

2021-01-08 13:44 UTC, florian-h05 commented on includes/frontail-theme.css
> +@import 'default.css';
First I thought that I need that change because of tests on my machine, but everything is fine when using the url.
Thank you for your review

2021-01-08 16:43 UTC, mstormi commented
Sorry but that's not the right way to contribute.
You changes would need to be against master (not openHAB3), above you can see what happens if you don't.
So please re-do again with master. And you must not merge anything into your branch as we need to keep commit history clean.

2021-01-08 18:57 UTC, florian-h05 commented
Okay, no problem

2021-01-08 19:23 UTC, closed without merging