re-add default mosquitto auth config on setup
openhab/openhabian pull request #1649
Opened 2022-01-17 19:58 UTC by mstormi

Signed-off-by: Markus Storm <markus.storm@gmx.net>

2022-01-17 21:47 UTC, ecdye requested changes
Not sure what the point of this is other than to use variable to point to the files, care to elaborate?

2022-01-17 21:47 UTC, ecdye commented on functions/packages.bash
> +
Remove extra line.

2022-01-17 21:47 UTC, ecdye commented on functions/packages.bash
> +    echo -n "" > ${mosquittoPasswd}
Perhaps a more elegant solution would be to use `touch`?
```suggestion
    touch ${mosquittoPasswd}
```

2022-01-18 06:01 UTC, mstormi commented
> Not sure what the point of this is other than to use variable to point to the files, care to elaborate?



> Not sure what the point of this is other than to use variable to point to the files, care to elaborate?

[This](https://community.openhab.org/t/oh3-mqtt-setup-and-configuration/111494#h-1a-configure-newer-versions-of-mosquitto-4) essentially has changed since our mosquitto implementation. So you cannot connect MQTT clients with the default config, it's what some beginners stumble across

2022-01-18 06:14 UTC, mstormi commented
wonder why BATS failed (on some ztab related line) but this is unrelated to this change

2022-01-18 17:45 UTC, ecdye commented
That is a change I made in zram, I'm working on fixing it don't worry about it.

2022-01-18 17:45 UTC, ecdye approved these changes
LGTM

2022-01-18 17:46 UTC, merged