add Zulu JDK 21 installation on 64bit
openhab/openhabian pull request #1861
Opened 2024-04-02 18:03 UTC by holgerfriedrich

Requires a native 64 bit image, running a 64 bit kernel with 32-bit OS is not sufficient.

I have been working to make OH compile an run with Java21 openhab/openhab-distro#1590. Not all of the required PRs have been merged, so we are not yet there.
This PR allows to install Java21 on x64/aarch64 systems.

Running the snapshot distro without modification is not yet possible, still waiting for the PR openhab/openhab-distro#1640
 to be merged.

2024-04-04 15:45 UTC, mstormi requested changes
>Requires a native 64 bit image, running a 64 bit kernel with 32-bit OS is not sufficient.

Please add proper checks for this in the install routine to ensure it only installs when the prerequisites are met

2024-04-05 19:44 UTC, holgerfriedrich commented
Hi @mstormi,
I think the checks are already there, shared by the Zulu11-64 and Zulu 21-64 targets.
```if is_aarch64 || is_x86_64 && [[ $(getconf LONG_BIT) == 64 ]]; then``` 
The check with ```getconf``` is really necessary - I had my RPI image that showed aarch64 but LONG_BIT 32 with a 32 bit userland.

If the prerequisites are not met, the common error reaction is to show a message in interactive setup (good) or to install Zulu-32 in the interactive case (maybe not so well suited).
As the code for the fallback is shared and there is no Java 21 32bit available anyway, this might be ok.

WDYT?

Btw: anything wrong with my change which causes the bats test to fail, or are the tests affected by something else?

2024-04-05 20:16 UTC, mstormi approved these changes
That's fine then
no BATS test failing is unrelated

2024-04-05 20:17 UTC, merged

2024-04-05 20:18 UTC, holgerfriedrich commented
Thanks, Markus