Add support for route advertisments for Matter
openhab/openhabian pull request #1922
Opened 2024-10-23 01:00 UTC by ecdye

Fixes #1919

2024-10-23 12:44 UTC, mstormi approved these changes
lgtm

2024-10-23 14:42 UTC, lrabius commented
On a fresh install dhcpcd shouldn't be installed anymore, because it was replaced by NetworkManager with Raspi OS bookworm. But I don't know what happens to dhcpcd when you upgrade from an older Raspi OS.

Also it's called Router Advertisements :wink:

2024-10-23 15:32 UTC, mstormi commented
Not sure how it all relates but dhcpcd is still part of Raspi OS/bookworm, we don't install it on top

2024-10-23 19:47 UTC, lrabius commented
Yeah I know. Just wanted to mention that dhcpcd is no longer installed by default on new systems. So maybe the dhcpcd config isn’t needed at all. At the moment the script might fail on new systems when trying to restart dhcpcd because it isn‘t installed. Am 23.10.2024 um 17:33 schrieb Markus Storm ***@***.***>:﻿
Not sure how it all relates but dhcpcd is still part of Raspi OS/bookworm, we don't install it on top

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-10-23 19:52 UTC, mstormi commented
Apparently so.
Ethan eventually you can remove dhcpcd remainders with this PR, too?

2024-10-24 14:48 UTC, mstormi requested changes

2024-10-24 14:48 UTC, mstormi commented on includes/generic/50-timesyncd.conf
why deleted?
Wouldn't we (albeit the comment say dhcpcd created this, saw that) still need this for timesyncd to work ?
Had quite some nuisances when I had to touch that stuff last time.

2024-10-24 15:48 UTC, ecdye commented on includes/generic/50-timesyncd.conf
I actually deleted it because it wasn't actually being used anywhere in the codebase. We might have done stuff with it in the past but as of now, it's unused.

2024-10-25 07:00 UTC, mstormi commented on includes/generic/50-timesyncd.conf
on re-reading the code, okay
Just happened to have quite trouble with several installations in the near past that did not sync time or had an hour off or so, related to java which needs to run with -Duser.timezone=...

2024-10-25 07:01 UTC, mstormi approved these changes

2024-10-25 16:35 UTC, merged